local palette = require("focus-walker.palette")

local M = {}

function M.setup(opts)
	opts = opts or {}
	local bg = opts.transparent and palette.none or palette.bg
	local comments = opts.dim_comments and palette.comment_muted or palette.yellow

	return {
		Normal = { fg = palette.fg, bg = bg },
		NormalFloat = { fg = palette.fg, bg = palette.bg_darker },
		FloatBorder = { fg = palette.selection, bg = palette.bg_darker },
		Cursor = { fg = palette.bg, bg = palette.fg },
		CursorLine = { bg = palette.selection },
		CursorColumn = { bg = palette.selection },
		ColorColumn = { bg = palette.bg_darker },
		LineNr = { fg = palette.comment_muted, bg = bg },
		CursorLineNr = { fg = palette.yellow, bg = palette.selection },
		SignColumn = { fg = palette.comment_muted, bg = bg },
		EndOfBuffer = { fg = palette.selection, bg = bg },
		NonText = { fg = palette.selection },
		Whitespace = { fg = palette.selection },
		WinSeparator = { fg = palette.selection },
		VertSplit = { link = "WinSeparator" },
		Visual = { bg = palette.selection },
		VisualNOS = { link = "Visual" },
		Search = { fg = palette.bg, bg = palette.yellow, underline = true },
		IncSearch = { fg = palette.bg, bg = palette.purple },
		Substitute = { fg = palette.bg, bg = palette.green },
		MatchParen = { fg = palette.yellow, underline = true },
		Pmenu = { fg = palette.fg, bg = palette.selection },
		PmenuSel = { fg = palette.black, bg = palette.purple },
		PmenuSbar = { bg = palette.selection },
		PmenuThumb = { bg = palette.purple },
		StatusLine = { fg = palette.fg, bg = palette.selection },
		StatusLineNC = { fg = palette.comment_muted, bg = palette.bg_darker },
		TabLine = { fg = palette.fg, bg = palette.bg_darker },
		TabLineFill = { fg = palette.fg, bg = palette.bg_darker },
		TabLineSel = { fg = palette.bg, bg = palette.fg },
		Folded = { fg = comments, bg = palette.bg_darker },
		FoldColumn = { fg = palette.comment_muted, bg = bg },
		Directory = { fg = palette.blue },
		Title = { fg = palette.fg },
		Question = { fg = palette.fg },
		MoreMsg = { fg = palette.green },
		WarningMsg = { fg = palette.yellow },
		ErrorMsg = { fg = palette.red },

		Comment = { fg = comments },
		String = { fg = palette.green },
		Constant = { fg = palette.yellow },
		Number = { link = "Constant" },
		Boolean = { link = "Constant" },
		Float = { link = "Constant" },
		Character = { link = "Constant" },
		Function = { fg = palette.blue },
		Identifier = { fg = palette.fg },
		Statement = { fg = palette.fg },
		Keyword = { fg = palette.fg },
		Conditional = { fg = palette.fg },
		Repeat = { fg = palette.fg },
		Label = { fg = palette.fg },
		Exception = { fg = palette.red },
		Operator = { fg = palette.fg },
		Delimiter = { fg = palette.fg },
		Type = { fg = palette.fg },
		StorageClass = { fg = palette.fg },
		Structure = { fg = palette.fg },
		Typedef = { fg = palette.fg },
		PreProc = { fg = palette.purple },
		Include = { fg = palette.fg },
		Define = { fg = palette.purple },
		Macro = { fg = palette.purple },
		PreCondit = { fg = palette.purple },
		Special = { fg = palette.purple },
		SpecialChar = { fg = palette.yellow },
		SpecialComment = { fg = comments },
		SpecialKey = { fg = palette.selection },
		Tag = { fg = palette.cyan },
		Underlined = { underline = true },
		Todo = { fg = palette.bg, bg = palette.yellow },
		Error = { fg = palette.fg, bg = palette.red },
	}
end

return M
