local palette = require("focus-walker.palette")

local M = {}

function M.setup(opts)
	opts = opts or {}
	local bg = opts.transparent and palette.none or palette.bg
	local comments = opts.dim_comments and palette.comment_muted or palette.yellow

	return {
		Normal = { fg = palette.fg, bg = bg },
		NormalFloat = { fg = palette.fg, bg = palette.bg_darker },
		FloatBorder = { fg = palette.selection, bg = palette.bg_darker },
		Cursor = { fg = palette.bg, bg = palette.fg },
		CursorLine = { bg = palette.selection },
		CursorColumn = { bg = palette.selection },
		ColorColumn = { bg = palette.bg_darker },
		LineNr = { fg = palette.comment_muted, bg = bg },
		CursorLineNr = { fg = palette.yellow, bg = palette.selection },
		SignColumn = { fg = palette.comment_muted, bg = bg },
		EndOfBuffer = { fg = palette.selection, bg = bg },
		NonText = { fg = palette.selection },
		Whitespace = { fg = palette.selection },
		WinSeparator = { fg = palette.selection },
		VertSplit = { link = "WinSeparator" },
		Visual = { bg = palette.selection },
		VisualNOS = { link = "Visual" },
		Search = { fg = palette.bg, bg = palette.yellow, underline = true },
		IncSearch = { fg = palette.bg, bg = palette.purple },
		Substitute = { fg = palette.bg, bg = palette.green },
		MatchParen = { fg = palette.yellow, underline = true },
		Pmenu = { fg = palette.fg, bg = palette.selection },
		PmenuSel = { fg = palette.black, bg = palette.purple },
		PmenuSbar = { bg = palette.selection },
		PmenuThumb = { bg = palette.purple },
		StatusLine = { fg = palette.fg, bg = palette.selection },
		StatusLineNC = { fg = palette.comment_muted, bg = palette.bg_darker },
		TabLine = { fg = palette.fg, bg = palette.bg_darker },
		TabLineFill = { fg = palette.fg, bg = palette.bg_darker },
		TabLineSel = { fg = palette.bg, bg = palette.fg },
		Folded = { fg = comments, bg = palette.bg_darker },
		FoldColumn = { fg = palette.comment_muted, bg = bg },
		Directory = { fg = palette.blue },
		Title = { fg = palette.fg },
		Question = { fg = palette.fg },
		MoreMsg = { fg = palette.green },
		WarningMsg = { fg = palette.yellow },
		ErrorMsg = { fg = palette.red },

		Comment = { fg = comments },
		String = { fg = palette.green },
		Constant = { fg = palette.purple },
		Number = { link = "Constant" },
		Boolean = { link = "Constant" },
		Float = { link = "Constant" },
		Character = { link = "Constant" },
		Function = { fg = palette.blue },
		Identifier = { fg = palette.fg },
		Statement = { fg = palette.fg },
		Keyword = { fg = palette.fg },
		Conditional = { fg = palette.fg },
		Repeat = { fg = palette.fg },
		Label = { fg = palette.fg },
		Exception = { fg = palette.fg },
		Operator = { fg = palette.fg },
		Delimiter = { fg = palette.fg },
		Type = { fg = palette.fg },
		StorageClass = { fg = palette.fg },
		Structure = { fg = palette.fg },
		Typedef = { fg = palette.fg },
		PreProc = { fg = palette.fg },
		Include = { fg = palette.fg },
		Define = { fg = palette.fg },
		Macro = { fg = palette.fg },
		PreCondit = { fg = palette.fg },
		Special = { fg = palette.fg },
		SpecialChar = { fg = palette.fg },
		SpecialComment = { fg = comments },
		SpecialKey = { fg = palette.selection },
		Tag = { fg = palette.fg },
		Underlined = { underline = true },
		Todo = { fg = palette.bg, bg = palette.yellow },
		Error = { fg = palette.fg, bg = palette.red },

		["@comment"] = { link = "Comment" },
		["@string"] = { link = "String" },
		["@string.documentation"] = { link = "String" },
		["@string.escape"] = { fg = palette.yellow },
		["@character"] = { link = "Constant" },
		["@number"] = { link = "Constant" },
		["@number.float"] = { link = "Constant" },
		["@boolean"] = { link = "Constant" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Constant" },
		["@constant.macro"] = { fg = palette.fg },
		["@function"] = { link = "Function" },
		["@function.call"] = { link = "Function" },
		["@function.builtin"] = { link = "Function" },
		["@function.macro"] = { fg = palette.fg },
		["@constructor"] = { fg = palette.fg },
		["@module"] = { fg = palette.fg },
		["@type.definition"] = { link = "Function" },
		["@variable"] = { fg = palette.fg },
		["@variable.builtin"] = { link = "Constant" },
		["@variable.parameter"] = { fg = palette.fg },
		["@property"] = { fg = palette.fg },
		["@field"] = { fg = palette.fg },
		["@keyword"] = { fg = palette.fg },
		["@keyword.function"] = { fg = palette.fg },
		["@keyword.return"] = { fg = palette.fg },
		["@keyword.conditional"] = { fg = palette.fg },
		["@keyword.repeat"] = { fg = palette.fg },
		["@operator"] = { fg = palette.fg },
		["@punctuation.delimiter"] = { fg = palette.fg },
		["@punctuation.bracket"] = { fg = palette.fg },
		["@punctuation.special"] = { fg = palette.fg },
		["@markup.heading"] = { fg = palette.blue },
		["@markup.link"] = { fg = palette.blue, underline = true },
		["@markup.raw"] = { fg = palette.green },

		DiagnosticError = { fg = palette.red },
		DiagnosticWarn = { fg = palette.yellow },
		DiagnosticInfo = { fg = palette.cyan },
		DiagnosticHint = { fg = palette.cyan },
		DiagnosticOk = { fg = palette.green },
		DiagnosticUnderlineError = { underline = true, sp = palette.red },
		DiagnosticUnderlineWarn = { underline = true, sp = palette.yellow },
		DiagnosticUnderlineInfo = { underline = true, sp = palette.cyan },
		DiagnosticUnderlineHint = { underline = true, sp = palette.cyan },
		DiagnosticUnnecessary = { fg = palette.comment_muted, underline = true, sp = palette.blue },

		DiffAdd = { fg = palette.green },
		DiffAdded = { link = "DiffAdd" },
		DiffDelete = { fg = palette.red },
		DiffRemoved = { link = "DiffDelete" },
		DiffChange = { fg = palette.yellow },
		DiffText = { fg = palette.fg, bg = palette.selection },

		LspReferenceText = { bg = palette.selection },
		LspReferenceRead = { bg = palette.selection },
		LspReferenceWrite = { bg = palette.selection },

		MiniStatuslineModeNormal = { link = "DiffAdd" },
		MiniStatuslineModeVisual = { link = "DiffDelete" },
		MiniStatuslineModeInput = { link = "DiffChange" },
		MiniStatuslineModeInsert = { link = "DiffChange" },
		MiniStatuslineModeCommand = { fg = palette.black, bg = palette.purple },
		MiniStatuslineModeOther = { fg = palette.black, bg = palette.cyan },

		TelescopeNormal = { link = "NormalFloat" },
		TelescopeBorder = { link = "FloatBorder" },
		TelescopePromptNormal = { link = "NormalFloat" },
		TelescopePromptBorder = { link = "FloatBorder" },
		TelescopePromptTitle = { fg = palette.black, bg = palette.green },
		TelescopePreviewTitle = { fg = palette.black, bg = palette.blue },
		TelescopeResultsTitle = { fg = palette.black, bg = palette.purple },
		TelescopeSelection = { bg = palette.selection },
		TelescopeMatching = { fg = palette.yellow },
	}
end

return M
