##### Terminal / shell #########################################################

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",tmux-256color:RGB"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

set-option -g default-shell /opt/homebrew/bin/fish
set -g mouse on
set -g focus-events on

# Remove delay for exiting insert mode with ESC in Neovim.
set -sg escape-time 10

# Enable CSI-u / extended keys.
set -g extended-keys on
set -g extended-keys-format csi-u
set -g allow-passthrough on

##### Prefix / reload #########################################################

set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

unbind r
bind-key r source-file ~/.tmux.conf

##### Session / window options ################################################

set-window-option -g mode-keys vi
set -wg automatic-rename on
set -g automatic-rename-format "Window"
